### ISSUE TITLE
RFP - iriun

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1047]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://iriun.com/
Direct download URL for the software / installer : https://1758658189.rsc.cdn77.org/WinWebcam-2.6.8.exe
Software summary / short description:
webcam emulation for Windows

**Comment by dtantono** [comment]
I don't know there is a pending submission for this app because I already checked this (https://community.chocolatey.org/packages?q=iriun&moderatorQueue=&moderationStatus=all-statuses&prerelease=true&sortOrder=relevance) and it shows nothing. I hope these submission will be done soon

**Comment by AdmiringWorm** [comment]
Apologies for this issue not having a response, and that it has taken so long.
To answer your confusion.

The package is unlisted, meaning it does not show up in any searches for the package, and can only be detected when navigating directly to the package.

However, since the package exists I will be closing this issue, please follow the package triage documentation for further actions on this package: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process
