### ISSUE TITLE
RFP - cuetools

### ISSUE THREAD

**Issue by damian101** [chocolatey-community/chocolatey-package-requests#1165]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://cue.tools/wiki/Main_Page
Direct download URL for the software / installer : https://github.com/gchudov/cuetools.net/releases/download/v2.1.9/CUETools_2.1.9.zip
Software summary / short description: CUERipper can extract digital audio from audio CDs. It is an alternative to EAC. CUETools can verify, reencode and repair existing audio CD rips. Both allow adding metadata from MusicBrainz and freeDB metadata databases, and verify rips with checksums from AccurateRip and CTDB databases.

## Package Expectations
This is a collection of three applications, CUETools, CUERipper and BluTools. All three should be installed by installing this package.

**Comment by pauby** [comment]
This does look like exactly the same software, however the package hasn't been updated since last February so following the [triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) in the first instance would be the best course of action.

I'm going to go ahead and close this, but we can reopen if necessary.
