### ISSUE TITLE
RFM - keepass-plugin-passwordcounter

### ISSUE THREAD

**Issue by FoxInTheClouds** [chocolatey-community/chocolatey-package-requests#1183]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/keepass-plugin-passwordcounter
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/keepass-plugin-passwordcounter/0.1

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Email

**Comment by pauby** [comment]
I will pick this one up.

**Comment by pauby** [comment]
I came to update the package and found that the latest version is 0.1, which is the same as what is on the Chocolatey Community Repository. The last version was released in 2014 so I don't see any new versions being released.

As there is nothing to do here, I'll close the issue here and the issue over on my repository.
