### ISSUE TITLE
RFM - keepass-plugin-keepasshttp

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1209]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/keepass-plugin-keepasshttp
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/keepass-plugin-keepasshttp/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by pauby** [comment]
I came to update the package and found that the [latest version is 1.8.4.2](https://github.com/pfn/keepasshttp/tags), which is the same as what is on the [Chocolatey Community Repository](https://community.chocolatey.org/packages/keepass-plugin-keepasshttp). The [last version was released in 2017](https://github.com/pfn/keepasshttp/tags), so I don't see any new versions being released in the future.

As there is nothing to do here, I'll close the issue here and the issue over on my repository.
