### ISSUE TITLE
RFP - tenacity

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1331]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/tenacityteam/tenacity
Direct download URL for the software / installer :https://nightly.link/tenacityteam/tenacity/workflows/cmake_build/master/Tenacity_windows-server-2019-amd64-x64_windows-ninja_2027403619_.zip
Software summary / short description:
an open source alternative of sound editor app

**Comment by pauby** [comment]
@dtantono You have created a [number of package requests recently](https://github.com/chocolatey-community/chocolatey-package-requests/issues?q=is%3Aissue+author%3Adtantono) that all already exist as packages on the Chocolatey Community Repository. Please follow the instructions given to you when raising a request and check the [Chocolatey Community Repository](https://community.chocolatey.org/packages) for packages _before_ raising a request. Each time you do not do this, it wastes the time of the maintainers of this repository.

Thanks.

**Comment by dtantono** [comment]
@pauby well it is not yet approved and it does not appear on the search. So, I don't know that. Thanks
![image](https://user-images.githubusercontent.com/29157187/170607682-ac87fc5c-50ae-4350-b95a-6d5338c9720e.png)

**Comment by pauby** [comment]
@dtantono This issue is not specifically linked to this request. As I linked to in my last message there have been a number of invalid requests. Had this been the only one, I wouldn't have mentioned it.

With regards to the tenacity package, there are two prerelease versions already available:

![image](https://user-images.githubusercontent.com/12760779/170794620-c43cbcf9-16c2-464e-b890-710413b055e3.png)

Which you can find by using the 'Include prerelease' option:

![image](https://user-images.githubusercontent.com/12760779/170794547-293b207e-6fd6-40e5-9fa5-29dafef0fdab.png)

**Comment by dtantono** [comment]
well, last time I checked it there is nothing in the search and that is fast. because it takes longer than that and also most of my invalid requests are stuck in the pending approval status from different persons and I don't know about it in the first place. So, it cannot be helped.

**Comment by pauby** [comment]
> So, it cannot be helped.

Comments like this don't help us maintain the repository. If you are going to keep rasing invalid requests because you are not checking that packages already exist then it puts a burden and additional workload onto us. Please check that the package exists in future so that you don't raise invalid requests.
