### ISSUE TITLE
RFP - insomnia-sleep

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1359]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://dlaa.me/Insomnia/
Direct download URL for the software / installer : https://dlaa.me/Samples/Insomnia/Insomnia.zip
Software summary / short description:   The default power settings for Windows are configured so a computer will go to sleep after 15-30 minutes of inactivity (e.g., no mouse or keyboard input). This is great because a computer that's not being used doesn't need to be running at full power. By letting an idle machine enter sleep mode, the user benefits from a significant reduction in electricity use, heat generation, component wear, etc.. And because sleep preserves the state of everything in memory, it's quick to enter, quick to exit, and doesn't affect your workflow. All the same applications continue running, windows stay open and where they were, and so on. Sleep mode is a Good Thing.

**Comment by brogers5** [comment]
It looks like there was a package submitted for moderation some years ago, but was ultimately abandoned and rejected:
https://community.chocolatey.org/packages/insomnia

I can pick this one up, but having ran into this situation before, seems like we'll need to get the Package Triage Process started.

**Comment by brogers5** [comment]
I reached out to the maintainer shortly after my last comment, and have yet to hear back. As the normal 7 day waiting period is up, I've submitted a request to the admins to be added as a maintainer.

The software has not been updated since the original package submission. Therefore, I've also requested to pick up the rejected package version, so I can submit a revised package under the same package version.

I've been working on a new and improved package for the native binaries in parallel, and should have it ready for review soon.

FYI, I'm planning to support the .NET binary in a separate package. Although both the native binaries and .NET binary are distributed within the same ZIP archive, they have conflicting version information (namely the version number and copyright statement), and the .NET binary has an extra dependency on .NET Framework 3.5.

**Comment by brogers5** [comment]
Packages have been submitted and are now pending review:
https://community.chocolatey.org/packages/insomnia/1.1.0.0
https://community.chocolatey.org/packages/insomnia-dotnet/1.0.0.0

**Comment by brogers5** [comment]
`insomnia-dotnet` has been approved and should now be live for consumption.

`insomnia` is still awaiting review.

**Comment by brogers5** [comment]
`insomnia` has recently been approved and should now be live for consumption.

Issue can now be closed.

**Comment by soredake** [comment]
@brogers5 thank you!
