### ISSUE TITLE
RFP - remote-desktop-client

### ISSUE THREAD

**Issue by denovellis** [chocolatey-community/chocolatey-package-requests#1365]
## Checklist

- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop
Direct download URL for the software / installer : https://go.microsoft.com/fwlink/?linkid=2068602
Software summary / short description: You can use the Remote Desktop client for Windows Desktop to access Windows apps and desktops remotely from a different Windows device.

**Comment by dgalbraith** [comment]
I will pick this one up.

**Comment by dgalbraith** [comment]
@denovellis the package is built and ready to be pushed but just a final point on naming - windows-desktop-client doesn't really seem appropriate as it does not convey the purpose of the package.

I am thinking of pushing as remote-desktop-client - given this is a desktop implementation of RDS / MSRDC I think that this is likely most appropriate.  Do you have any concerns or an alternate suggestion on this?

**Comment by denovellis** [comment]
It is perfect for me.

**Comment by dgalbraith** [comment]
The package is pushed and awaiting review:

- https://community.chocolatey.org/packages/remote-desktop-client/1.2.3497

Note that it is currently failing package verification and a moderator needs to consider the verification exemption request.  I believe that the verification failure is due to a reboot required by the package dependencies.

The package is good as-is on any machine which has a DotNet 4.6.0 or later runtime available.

**Comment by dgalbraith** [comment]
Initial review has been completed and the package is now available in the Community Repository.

https://community.chocolatey.org/packages/remote-desktop-client/
