### ISSUE TITLE
RFM - Goodsync

### ISSUE THREAD

**Issue by arberg** [chocolatey-community/chocolatey-package-requests#312]
https://chocolatey.org/packages/GoodSync

Package currently installs the old v9, not the new v10. All that needs to happen (it seems) is to update the url

v9: https://www.goodsync.com/download/GoodSync-Setup.msi
v10: https://www.goodsync.com/download/GoodSync-v10-Setup.msi 

Package-maintainer is unresponsive, and it sounds like an issue like this is the way forward.

**Comment by pauby** [comment]
As this looks fairly straightforward I'll pick this one up.

**Comment by pauby** [comment]
New release for this package was published on 10 April so it's been picked back up.

**Comment by arberg** [comment]
The current release (as of 14/4) still has the incorrect url

$url = 'https://www.goodsync.com/download/GoodSync-Setup.msi'

according to content of tools\chocolateyInstall.ps1 as seen on 

https://chocolatey.org/packages/GoodSync

Perhaps it was just auto-updated due to new goodsync release. I suspect there are bots doing updates, as it is what I would do.

Best Alex

**Comment by kerhbal** [comment]
So this issue has been closed for 10 months and your users are still getting stuck here. And no one seems to care about the pull-request made and left there for 10 months? Read the comments please. https://chocolatey.org/packages/GoodSync

**Comment by pauby** [comment]
@kerhbal I think there is some misunderstanding about this repository, this package and the Chocolatey Community Repository. Let me try and clear that up.

## This Repository

Here you raise issues for a package to be created (that doesn't exist) or for a new maintainer to take over a package that doesn't have an active maintainer.

## This Package

The package that this refers to is maintained by a volunteer who is known to be no longer maintaining his packages hence why this issue was created. The package does not belong to 'me' or 'us'.

## The Chocolatey.org Community Repository

This repository is a collection of over 6100 packages created and moderated by volunteers. The packages don't belong to Chocolatey but are for the community to maintain and manage.

My last message to @arbeg was to ask to submit a pull request to fix this package / update to the latest version so that it could be made available to the community again.

If you have an issue with a package you have three options:

1. Contact the maintainer (using the 'Contact Maintainer' on the package page) and ask them to fix it / update it;
2. Fix it / update it and raise a Pull Request for the maintainer to fix it / update it with your changes;
3. If the maintainer either does not respond to your contacting them or is known to be no longer maintaining the package you can raise a request here for somebody else to pick it up;
4.  If the maintainer either does not respond to your contacting them or is known to be no longer maintaining the package you can  use the 'Contact Site Admins's link on the package page to request to take over the package.

In this instance it would be best if somebody else picked this package up (and in this case we can re-open this issue). If you would like to pick it up please use the 'Contact Site Admins' link on the package page to request it and put this issue in as a reference.

Hopefully that explains how things work.

**Comment by pauby** [comment]
@kerhbal You make some good points. To try and keep this issue about this package it would be good to chat about them over at https://gitter.im/chocolatey/chocolatey.org.

To clarify this issue was closed on 29 April and the label removed as it was no longer needed (the label or the issue). Since that date 4 package versions have been published (with 10 in total in 2018). At the time it was thought the maintainer was back and maintaining the package. That's nto the case but his repository is being managed. But you make a good point that it should be reopened.

**Comment by arberg** [comment]
thank you for reopening, I've posted there for followup questions: https://gitter.im/chocolatey/chocolatey.org?at=5c49df63cb47ec3000961f32

**Comment by kerhbal** [comment]
@pauby Thank you for the response and understanding.

**Comment by mikecole** [comment]
I would be willing to pick up this package if needed. Sounds like we'd want to stop the ketarin pushes, so would that happen by revoking dtgm as maintainer?

**Comment by pauby** [comment]
When you are ready to push the new package raise a PR in dtgm repository to remove the package and the Ketarin files.

**Comment by mikecole** [comment]
@arberg Fair to say the only change needed is the source URL for the installer?

**Comment by arberg** [comment]
Sorry for being a bottleneck. 

The only change I had for the original script was an update of the URL. I have no idea that is required for the powershell based installer, but it seems likely it just an url, since I believe its a standard msi/exe installer. Well no I suppose there has to be a correct scraping of the download page, for the auto-update script. 

Best Alex

**Comment by pauby** [comment]
Has any progress been made on this @mikecole ?

**Comment by mikecole** [comment]
Sorry, I have not. I probably won’t until next week at the earliest.

**Comment by mikecole** [comment]
@pauby please move this back to available. I may pick it up again someday, but just don't have the time right now. Thanks!

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/goodsync

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/goodsync

**Comment by arberg** [comment]
Looks good to me. I've just run 'choco install goodsync' and reviewed the chocolateyinstall.ps1 and it looks good, it downloads correct goodsync and says it installed it.

Awesome chtof, thank you.

**Comment by chtof** [comment]
@arberg And this package is automatically updated, version 10.10.1 is coming! Thank you for your feedback!

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/goodsync

Can be closed.
