### ISSUE TITLE
RFP - Elmer FEM

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#488]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://www.elmerfem.org/blog/
Direct download URL for the software / installer : http://www.nic.funet.fi/pub/sci/physics/elmer/bin/windows/
Software summary / short description:  From their website

> Elmer is a finite element software for multiphysical problems published under open source.

**Comment by pauby** [comment]
Download location for the installer is at https://sourceforge.net/projects/elmerfem/files/

**Comment by Foadsf** [comment]
@pauby I'm trying to edit this post and use the official template, but I can't. Would you be kind to provide me with the official template if it is available somewhere? (I tried opening a new RFP to copy past from there but it shows a blank issue request!)

**Comment by Foadsf** [comment]
It seems the [FUNET link](http://www.nic.funet.fi/pub/sci/physics/elmer/bin/windows/) is a better place for downloading. There are `nightly` and stable binaries.

**Comment by Foadsf** [comment]
options:

- `--nightly`, `--stable`
- `--with-mpi`, `--without-mpi`

**Comment by pauby** [comment]
@foadsf It's blank for me too. I'm hoping this is a temp GitHub issue as it's very strange.

In the meantime you can find the template at https://raw.githubusercontent.com/chocolatey-community/chocolatey-package-requests/master/.github/ISSUE_TEMPLATE/kPackageRequest.md

**Comment by chtof** [comment]
Status: **In progress**
https://chocolatey.org/packages/elmer

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/elmer
https://chocolatey.org/packages/elmer-mpi

@Foadsf:
- These 2 packages should be tested (as I didn't find easily how to use Elmer FEM).
- For nightly versions:
  - Note: The latest nightly version has been released several months ago.
  - For nightly versions, the problem is the nightly installers don't contain a timestamp so if we release nightly versions, it will be more difficult to detect new releases.

**Comment by Foadsf** [comment]
Dear @chtof sure I will test them. Would you be kind to provide me with the testing instructions? Also @raback , one of the Elmer's core developers, should also be interested in this.

**Comment by chtof** [comment]
Hello @Foadsf @raback, I recommend to test them once they will be validated (they are currently under review). Once validated, repeat these steps for elmer and elmer-mpi* packages (so, twice):
- Install elmer and/or elmer-mpi: `choco install [elmer|elmer-mpi]`
- Test the application (are you able to use the software like an user will do) and specially the main features of the application (I think remember you have to import "mesh" to use the app). You are welcome to report any error messages (keep screenshots and error messages and when the error occurs in case I need further information later).
- Uninstall elmer and/or elmer-mpi: `choco uninstall [elmer|elmer-mpi]`
_*Note: For elmer-gui, try to use a feature which requires to call "Microsoft MPI" libraries to see if it works as expected._

If everything works as expected and you want to have elmer on your computer, you have just to install again elmer or elmer-mpi.

**Comment by Foadsf** [comment]
Dear @chtof couldn't we have options instead of different pckages as I decribed [above](https://github.com/chocolatey-community/chocolatey-package-requests/issues/488#issuecomment-598865732)?

**Comment by chtof** [comment]
@Foadsf Disavantages:
- Can't be embedded if all-in-one package (each installer is about 120 MB and the max size of an embedded comunity package is 200 MB).
- If all-in-one package, only one installer will be scanned by VirusTotal due to technical reasons.
- How to handle packages with different versions in only one package?
- When you haven't the Business edition of Chocolatey, it's a little bit difficult to use switches.

Or what about a single installer for Elmer with switches?
