### ISSUE TITLE
RFP - GeoGebra Graphing Calculator

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#575]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.geogebra.org/download
Direct download URL for the software /installer: https://download.geogebra.org/package/windows-graphing
Software summary / short description: Currently there are only the older GeoGebra 5 and 6 versions(rebranded to classic versions on their website) available on the community repo. GeoGebra graphing calculator is basically GeoGebra 7.

https://chocolatey.org/packages/geogebra6
https://chocolatey.org/packages/geogebra

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/graphingcalculator

**Comment by chtof** [comment]
Status: **In progress**
- Updated package ready: https://github.com/chtof/chocolatey-packages/tree/master/automatic/graphingcalculator (but probably to rename to geogebra6, see below).

Due to a mistake with another RFP, I have pusblished GeoGebra Graphing Calculator with the name of "graphingcalculator". Maybe we should reject this last one and I should contact maintainer of geogebra6 to see if he wants to update the package.
@TheCakeIsNaOH _GeoGebra graphing calculator is basically GeoGebra 7._ : I haven't seen another file than GeoGebraGraphing-Windows-Installer-6-0-535-0.exe so Version 6. Where have you seen a version 7 to download?

**Comment by TheCakeIsNaOH** [comment]
That was not worded ideally @chtof, sorry about that.

I should say that it is the next major version of GeoGebra, not that it is v7. However, they probably should have called it version 7, but instead, they keep the version 6 naming.

**Comment by chtof** [comment]
Status: **Published**

https://chocolatey.org/packages/geogebra6/6.0.535.0

Can be closed.
