### ISSUE TITLE
RFP - ccache

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#626]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://ccache.dev/  
Direct download URL for the software / installer: https://github.com/ccache/ccache/releases/tag/v3.7.1  
Software summary / short description:  
*ccache (or “Ccache”, not “CCache”) is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.*

*ccache is free software, released under the GNU General Public License version 3 or later. See also the license page.*

**Comment by pauby** [comment]
@luzpaz Is there a Windows binary for this? I may be looking too hard but I can't see one?

**Comment by mkevenaar** [comment]
Based on the documentation, you need to build this software:

https://github.com/ccache/ccache/blob/master/doc/INSTALL-from-release-archive.md

**Comment by luzpaz** [comment]
You're right. I found an unofficial binary, but it's not supported by upstream `ccache`. Would it be possible to use: 
https://github.com/fastbuild/fastbuild instead (from http://fastbuild.org/) ?

**Comment by pauby** [comment]
@luzpaz As long as we can verify an online version somewhere against anything that's embedded I'd be semi-happy with that.

The reasons behind this is obviously you could compile anything in there and then distribute it and claim it's the official build. 

If you compiled your own version, added the instructions on how to verify it by downloading from your 'unoffocial' site and also the instructions on how to compile it ourselves (so a user / moderator would want to actually compile your code and make sure it matches) and also add a line int eh description that this is an 'unofficial' build, then I would be happy with that. I know that's a lot of work but what we're trying to do is give the user confidence that mods have checked it but they can do so themselves in the knowledge that this is the way we have to do it because the official site doesn't distribute a binary.

You're ticking all the boxes at that stage. This isn't something I've come across but I'm sure there are packages out there that are in the same boat that @AdmiringWorm and @gep13 have come across.

**Comment by luzpaz** [comment]
I can't do that at this time. I will close this and open a new ticket for fastbuild

**Comment by pauby** [comment]
@luzpaz don't close this ticket as we'll need to know what's happening. If it turns out this can't be done in any way, then we can close it and label or accordingly.

**Comment by luzpaz** [comment]
Checkout https://github.com/nagayasu-shinya/ccache-win64/issues/4#issuecomment-511234552

**Comment by pauby** [comment]
@luzpaz Can you keep us up to date on whether the developer does start publishing compiled binaries?

**Comment by luzpaz** [comment]
@pauby do we want both 32 and 64 bit or just 64 ?

**Comment by pauby** [comment]
@luzpaz If we can do both then I think both makes most sense. If he only wants to do one then the x86 version again makes most sense (as it covers both x86 and x64).

However, it would entirely be up to the package maintainer - those are only my suggestions!

**Comment by AdmiringWorm** [comment]
I would say if possible, then support both 32bit and 64bit for this software.

If that isn't possible, then I would say only 64bit (as this is a caching for C/C++ compilers, I would say it is more likely that a the person using it is running 64bit, than 32bit and since 32bit is being phased out more and more).

**Comment by luzpaz** [comment]
> We (the ccache project) are currently discussing the future of ccache Windows support. One major problem with the Windows/MinGW support is that we test that it's possible to build ccache with MinGW but the test suite is not run, so it's very possible that new versions could introduce runtime bugs that are unknown at the time of release.

per @jrosdahl 

Relevant issues:  
* https://github.com/ccache/ccache/issues/430  
* https://github.com/nagayasu-shinya/ccache-win64/issues/4#issuecomment-513537555

**Comment by jrosdahl** [comment]
See also ccache/ccache#447.

**Comment by pauby** [comment]
@jrosdahl Given the updates on the linked issue, what is the status of this Chocolatey package request?

**Comment by jrosdahl** [comment]
> @jrosdahl Given the updates on the linked issue, what is the status of this Chocolatey package request?

Nothing has changed, really. Given the current status of the ccache Windows port (no automated tests and nobody stepping forward to drive Windows aspects), I'm not confident in creating official Windows binary releases since the state for me is kind of unknown. If somebody else would like to act as the maintainer of a Chocolatey package and at least make some rudimentary testing before publishing, I'm all for it. Perhaps @cristianadam would be interested?

See also https://github.com/ccache/ccache/issues/490.

**Comment by pauby** [comment]
@jrosdahl Whatever binaries are created they need to be official but let me clarify what I mean:

* If the binaries come from the official project then we can verify the checksums from the ones on GitHub (for example) and therefore confirm they are official;
* If the binaries _do not_ come from the official project then we still need to verify them. One way to do that would be to have the ability to compile them ourselves, from the official source code. If the checksums then match we're good to go;

If there is no way forward for this package then I think we would be best to close it. If there is still an option for a package to be created I'm minded to open it back up to Maintainers.

Thoughts?

/cc @AdmiringWorm

**Comment by AdmiringWorm** [comment]
> If the binaries do not come from the official project then we still need to verify them. One way to do that would be to have the ability to compile them ourselves, from the official source code. If the checksums then match we're good to go;

This will most likely not work. No two builds will have exactly the same checksum AFAIK.
Mostly due to metadata being compiled together with with the actual binaries (at least with MSVC, but probably with clang and GCC as well).
So any compilation would need to be done as part of the chocolatey installation procedure in that case.

**Comment by pauby** [comment]
> This will most likely not work. No two builds will have exactly the same checksum AFAIK.

I moderated a package some time ago and I did compile and I did get the same checksum so it is possible. But if that is the exception and compiling from source during installation is not an option, it's going to be tough to create a package.

**Comment by jrosdahl** [comment]
I wrote:
> I'm not confident in creating official Windows binary releases since the state for me is kind of unknown.

I should perhaps clarify this a bit. Just building Windows binaries from the official source code and publishing them in an official place would likely be fine. And doing so would arguably be better than having users finding and using unofficial binaries from some corner of the internet.

What I'm not confident in is saying is that the Windows binaries actually work since I won't test them before a release. This means that if there are Windows binaries there needs to be somebody who tests them before submitting them to Chocolatey. If that's how it works; forgive me for not having time to read up on Chocolatey.

**Comment by pauby** [comment]
@jrosdahl Can I just clarify:

* The project is not going to officially support Windows binaries (by support I mean out much effort into making sure everything works under Windows);
* The project is not confident in any official Windows binaries it produces;
* Any Windows binaries that are released will not be tested prior to being released;

**Comment by jrosdahl** [comment]
@pauby: Not sure I understand. Do you need more information from me?

**Comment by pauby** [comment]
@jrosdahl I'm looking to clarify the points I made [above](https://github.com/chocolatey-community/chocolatey-package-requests/issues/626#issuecomment-587365931) with a **yes** or **no**.

**Comment by pauby** [comment]
If there is no further update on this my intention would be to close it with "Can't implement" soon.

**Comment by jrosdahl** [comment]
> If there is no further update on this my intention would be to close it with "Can't implement" soon.

I planned to respond to this after making the next release, but here goes.

> @jrosdahl I'm looking to clarify the points I made above with a yes or no. That lets us understand what the next step would be.

OK. (I guess this could be a language issue – non-native English speaker here. I didn't interpret "Can I just clarify" as "Can _you_ just clarify", and the points are statements, not questions. I also wasn't 100% sure whether "the project" referred to ccache or Chocolatey.)

That said, I find it a bit hard to comment on your statements as written but I'll try my best.

> The project is not going to officially support Windows binaries

I actually plan to make an attempt to publish official 64-bit and 32-bit Windows binaries for the next release and see how it goes. I have come to think that that would be better than users finding and using unofficial binaries from some corner of the internet.

> (by support I mean out much effort into making sure everything works under Windows);

This will however still largely be true. What I can and intend to do with my limited resources is to build and run a simple unit test suite for the binaries. I currently don't have any integration tests for the Windows case, which is why I can't put much effort into making sure _everything_ works. 

I've now tried to document this "support level" and other aspects here: https://ccache.dev/platform-compiler-language-support.html

> The project is not confident in any official Windows binaries it produces;

This cannot be answered with a simple true/false or yes/no. I'm fairly confident that ccache works OK _in practice_ on Windows since some people seem to use it successfully. I'm just not confident in saying that each Windows binary is thoroughly tested before release (since they aren't).

> Any Windows binaries that are released will not be tested prior to being released;

I don't understand the practical difference between this and the previous statement. (Can a project be confident in anything without testing?) Please clarify if I'm missing something.

**Comment by pauby** [comment]
@jrosdahl
>> Any Windows binaries that are released will not be tested prior to being released;
> I don't understand the practical difference between this and the previous statement. (Can a project be confident in anything without testing?) Please clarify if I'm missing something.

My question was quoting what you had said [previously](https://github.com/chocolatey-community/chocolatey-package-requests/issues/626#issuecomment-585414621):

> What I'm not confident in is saying that the Windows binaries actually work since I won't test them before a release.

As long as the lack of testing is pointed out in the description of the package (because there is a high expectation that software would be tested / work whereas the expectation here is lower) then I think this would be good as a package.

Is there an ETA on this?

**Comment by jrosdahl** [comment]
> Is there an ETA on this?

Version 3.7.8 with (kind of experimental) Windows binary releases is now available.

**Comment by pauby** [comment]
I've made this to maintainers now. Thanks for the update @jrosdahl

**Comment by Xav83** [comment]
Hi everyone !

As a `ccache` user this package is really interesting me.

I may have skipped some steps, but, since I am new to this (I am just starting to upload my first package for `conan`), so I wanted to see if I could pull it off before committing to be the maintainer of a second packages.

And, well, I have now a package pending [here](https://chocolatey.org/packages/ccache/3.7.9) ^^

@pauby Is there something I should do to tell that I am currently working on having creating this chocolatey package ?

**Comment by pauby** [comment]
If you just let us know when you have picked up the package, when you've submitted it to the Chocolatey Community Repository and when it's been approved then we can update the status on the issue as we go along.

**Comment by Xav83** [comment]
Great ! I will do that ! So I pick up this package 🙂

**Comment by Xav83** [comment]
For information @jrosdahl, the chocolatey package is currently in the review process.
You can follow it [here](https://chocolatey.org/packages/ccache/3.7.9)

**Comment by Xav83** [comment]
Le package pour `ccache` vient d'être validé, et est désormais disponible.
Voici le lien vers la page du package => https://chocolatey.org/packages/ccache
