### ISSUE TITLE
RFM - Tomcat

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey-community/chocolatey-package-requests#63]
https://chocolatey.org/packages/Tomcat/8.0.33

**Comment by AdmiringWorm** [comment]
Seems like this one is still being maintained, as such closing this for now.

**Comment by AdmiringWorm** [comment]
nvm, missed the year it was submitted. Re-Opening.

**Comment by franklinyu** [comment]
I think this issue can be re-opened. skyguy94/chocolatey-packages#13 and skyguy94/chocolatey-packages#16 is open for quite some time. I wrote to maintainer through “contact maintainer” today, but I doubt it would be any better than GitHub issue and pull request.

**Comment by FranklinYu** [comment]
I’m thinking about picking this up, but the current version is poorly written:

 1. It extracts the zip file to `$env:ProgramFiles` and `${env:ProgramFiles}` for no obvious reason.
 1. There is a `chocolateyHelpers.ps1` sourced *only once*. It has only 15 lines.
 1. Every time user upgrade, new version is installed, without overwriting old version. For example, if user upgrade from `8.0.33` to `8.5.12` and decide to uninstall, the version `8.0.33` will remain *without user even noticing it*. Imagine user upgrade 10 times.
 1. Icon doesn’t pin the commit hash, and it is currently 404.
 1. Bug tracker URL points to the *package* bug tracker, instead of software bug tracker.
 1. The release note URL is same as project URL.

Shall I re-write it from scratch?

**Comment by AdmiringWorm** [comment]
I would say yes. Rewrite it completely, maybe have a fallback to the programs directories if the user already have it installed. However, everything is up to you to decide what to do (if you pick up the package)

**Comment by pauby** [comment]
@FranklinYu Have you picked this up and working on it?

**Comment by FranklinYu** [comment]
@pauby Yes I'm working on it. No ETA though.

**Comment by pauby** [comment]
@FranklinYu Can you give us an update on this one?

**Comment by FranklinYu** [comment]
@pauby Still working on it. I was just back from my two-week vacation…

**Comment by pauby** [comment]
@FranklinYu Is there any progress on this you can share?

**Comment by FranklinYu** [comment]
@pauby Yes. If everything is going on well, I would be releasing this within a week. I still have some question about policy or implementation of chocolatey.org; I would raise them in Gitter channel. (Actually I raised one of them yesterday.)

**Comment by FranklinYu** [comment]
The package is finished. I just need to be a maintainer of the package.

**Comment by pauby** [comment]
@FranklinYu If you've not done it yet, can you send in the request via the 'Contact Site Admins' link on the package page? If you have done this already, ignore me 😄

**Comment by FranklinYu** [comment]
It’s under review.

https://chocolatey.org/packages/Tomcat/9.0.17

**Comment by mkevenaar** [comment]
A newer version then mentioned above (9.0.19) is published!
