### ISSUE TITLE
RFP - Kugou 

### ISSUE THREAD

**Issue by fox272** [chocolatey-community/chocolatey-package-requests#653]
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.kugou.com/
Direct download URL for the software / installer : http://download.kugou.com/download/kugou_pc
Software summary / short description :
KuGou (Chinese: 酷狗音乐) is a Chinese music streaming and download service established in 2004 and owned by Tencent Music. It is the largest music streaming service in the world, with more than 450 million monthly active users.

## Package Expectations
adding icons to the desktop

**Comment by fox272** [comment]
thanks for your help

**Comment by chtof** [comment]
Chocolatey package fails because Get-WebHeaders switch to HTTPS for download but the file can only been successfully downloaded in HTTP.
How to avoid to switch to HTTPS?

- Invoke-WebRequest -Uri "http://download.kugou.com/download/kugou_pc" : It works as expected
- Invoke-WebRequest -Uri "https://download.kugou.com/download/kugou_pc" : HTTP Status code 200 but It doesn't download the file.
- cinst kugou -dv -s "."
(...)
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Running Get-WebFileName -url 'https://download.kugou.com/download/kugou_pc' -defaultName 'kugouInstall.exe'
Using response url to determine file name. 'https://download.kugou.com/download/kugou_pc'
File name determined from url is 'kugou_pc'
Running Get-WebHeaders -url 'https://download.kugou.com/download/kugou_pc' -ErrorAction 'Stop'
Setting the UserAgent to 'chocolatey command line'
Request Headers:
  'Accept':'*/*'
  'User-Agent':'chocolatey command line'
Response Headers:
  'Connection':'keep-alive'
  'Keep-Alive':'timeout=20'
  'Content-Length':'0'
  'Content-Type':'text/plain'
  'Date':'Thu, 15 Aug 2019 19:44:15 GMT'
  'Server':'KugouCDN'

**Comment by AdmiringWorm** [comment]
Sounds like the same issue we have with the nlite package.
Only way currently around it is to embedd the software (if the licensing and size allows it).

Issue related: https://github.com/chocolatey/choco/issues/1221

I will mark this issue as blocked for now.

**Comment by pauby** [comment]
@chtof Has there been any progress on this or are you waiting for https://github.com/chocolatey/choco/issues/1221 ?

**Comment by chtof** [comment]
I didn't find any license to allow to embed the package. Close as something like can't fix?
