### ISSUE TITLE
RFP - Tesseract

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#657]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=Tesseract&moderatorQueue=&prerelease=true&sortOrder=relevance) on **<https://chocolatey.org/packages>**
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+Tesseract)
- [x] The issue title starts 'RFP — '
- [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

+ Software project URL: **<https://github.com/tesseract-ocr/tesseract>**
+ Direct download URL for 64-bit Windows installer: **<https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20190708.exe>** (links from [**here**](https://github.com/UB-Mannheim/tesseract/wiki), that [**described in official Tesseract wiki**](https://github.com/tesseract-ocr/tesseract/wiki#windows))
+ Direct download URL for 32-bit Windows installer: **<https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-alpha.20190708.exe>**
+ Have this software command-line interface (CLI)? Yes
+ If «yes» for previous question, what folder(s) must be added to the `PATH` environment variable? `.`
+ Software summary/short description: popular ([**29214 GitHub stars**](https://github.com/tesseract-ocr/tesseract/stargazers) for 19 August 2019) open source optical character recognition (OCR) engine for different operating systems; read [**Wikipedia article**](https://en.wikipedia.org/wiki/Tesseract_(software)) for more details.

### 3. Notes

In installation process user need to select `Additional script data` and `Additional language data`, if he need OCR not solely for English texts.

Thanks.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/tesseract

Hi @Kristinita, I have just submitted a Chocolatey package but it will install tesseract with default options, so in english. I tried to use an Autohotkey script but the problem is when you select all languages and scripts, 2 languages files are not available and you have to click on OK button to continue anyway the installation.
- A solution can be to unselect options corresponding to missing files but:
  - The package will fail if another language file disappears or is renamed.
  - It doesn't allow to easily add another languages which are not included in the installer.
- Under Linux, there are [packages for each language (131) and script (35)](https://github.com/tesseract-ocr/tesseract/wiki#linux) but I don't know if we can also create 166 Chocolatey packages. Or maybe to have a "language" package with all languages and a "script" package with all scripts? On other hand, keepass is a popular software and its Chocolatey package doesn't integrate other languages than english.
So, suggestions are welcome...

_Note: Languages and scripts can't be embedded in the package as their total size exceed 200 MB._

**Comment by Kristinita** [comment]
@chtof,

**Type: Clarifying question ❔ **

> I tried to use an AutoHotkey script but the problem is when you select all languages and scripts, 2 languages files are not available and you have to click on OK button to continue anyway the installation.

Is it a problem of Tesseract installer? If yes, maybe we will create issue to Tesseract [**issue tracker**](https://github.com/UB-Mannheim/tesseract/issues)?

Thanks.

**Comment by chtof** [comment]
@Kristinita [Issue opened](https://github.com/UB-Mannheim/tesseract/issues/24).

**Comment by stweil** [comment]
Instead of using the installer to download the Tesseract models (`*.traineddata` files), it might be easier to get them directly from https://github.com/tesseract-ocr/tessdata_fast.

**Comment by stweil** [comment]
The [package description](https://chocolatey.org/packages/tesseract#package-description) is outdated. So is the README of Tesseract which was used as the source of that description. Maybe I can update it soon.

**Comment by stweil** [comment]
I suggest updating the installer to the October version.

**Comment by chtof** [comment]
Hi @stweil, 
- Thank you for your help so I understand the issue with missing files should be solved soon. I think it's easier to install all language and script directly from the installer instead of to search after the URL where the files should be downloaded, download the language file(s), search in which directory the language file(s) should be copied, download the script file(s), search in which directory the script file(s) should be copied.
- Yes, the package description come from https://github.com/tesseract-ocr/tesseract/blob/master/README.md
- _I suggest updating the installer to the October version._ [5.0.0.20191010-alpha has just been just submitted](https://chocolatey.org/packages/tesseract/5.0.0.20191010-alpha) (files are also missing in this version as I wrote in the opened issue).
- As a suggestion, an installer option to choose to install all languages and scripts data can help us also to have a cleaner and more robust Chocolatey package (because currently, when the issue with the 2 missing files will be solved, we would have to use an Autohotkey script to be able to install silently Tesseract with all languages and scripts data options enabled in the installer).
