### ISSUE TITLE
RFP - siril

### ISSUE THREAD

**Issue by aster94** [chocolatey-community/chocolatey-package-requests#803]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package; 
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.siril.org/about/
Direct download URL for the software / installer : https://free-astro.org/download/Install_SiriL_0_9_12_64bits_EN-FR.exe
Software summary / short description: image stacking software for astrophotography

**Comment by Cossey** [comment]
I've got this one, please assign and change Status, thanks!

Since its GPL 3, the license terms allow redistribution. I will make this package *Embeddable* so no external download will be required, it will use the zip distribution from the website.

**Comment by aster94** [comment]
Great @Cossey also the version 1 should be near to the release

**Comment by Cossey** [comment]
Package submitted, awaiting moderation.

I am concerned however due to the package size being `100MB` that it seems that pushing to chocolatey from my cloud server seems to stall the auto-updater script and pushing always throws back a `524 origin timeout` error. 

If I will have to manually execute the script from my desktop, it will affect my ability to maintain it and keep it up to date in a timely matter.

**Comment by pauby** [comment]
@Cossey The package has failed validation.

**Comment by Cossey** [comment]
@pauby Thanks, I've been busy the past few days but I was in the middle of correcting the problem.

**Comment by Cossey** [comment]
Package has been waiting for review for a few weeks so it's up to the review team now to okay it.

**Comment by Cossey** [comment]
Package has been approved.
