### ISSUE TITLE
RFM - ddu

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#850]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/ddu
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/ddu/
Date the maintainer was contacted: 2020-06-10
How the maintainer was contacted: Contact maintainer form on chocolatey

**Comment by AdmiringWorm** [comment]
@TheCakeIsNaOH in the future, please remove the section mentioning `### Current Maintainer` and use the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard for the date (`YYYY-MM-DD`)

**Comment by TheCakeIsNaOH** [comment]
Sounds fine, but the issue template does not mention either of these requirements.

**Comment by AdmiringWorm** [comment]
@TheCakeIsNaOH I am aware, those aren't requirements right now but will when the validator is pulled in.

The reason I made those decisions when writing the validator is because:
1. I needed a way to determine certain actions based on the template, and having both the current maintainer and I don't want to become the maintainer would only confuse the validation.
2. It was easier to use a standard for the date instead of possibly parsing the date incorrectly (since there are so many ways to write a date internationally).

**Comment by TheCakeIsNaOH** [comment]
@AdmiringWorm I completely understand the need for specific formatting and validation, I was concerned about people not knowing about the requirements, but I see you added details about the requirements to the issue template in the PR, which looks good to me.

**Comment by tunisiano187** [comment]
Hello, i'll take this package too ;-)
Have a nice day

**Comment by tunisiano187** [comment]
Hello,
Can someone assign this one to me ? and add the triage label ?
It waiting for moderation.
Thank you
tunisiano

**Comment by AdmiringWorm** [comment]
@tunisiano187 I assume you mean the review label, as the triage label is for issues that aren't yet been made available to maintainers.

The statuses are as following:

- `Status: Incomplete Request` - The validator has found issues with the request that needs to be fixed
- `Status: Triage`
    1. The validator has not found issues, and requires a human to open it up for maintainers completely
    2. Or, a human has found issues with the request that needs to be cleared before opening it up to maintainers (this should be then accompanied with a comment of what needs to be completed)
- `Status: Available For Maintainer(s)` - The issue is now available to be picked up by anyone
- `Status: In Progress` - A user have picked up the request, and have started working on creating/updating the package
- `Status: Review` - A new/updated package have been pushed to chocolatey.org and is awaiting review
- `Status: Published` - The new/updated package has been approved/exempted on chocolatey.org, and request is completed.

**Comment by tunisiano187** [comment]
Yes, sorry.
Thank you

**Comment by TheCakeIsNaOH** [comment]
Approved. Thanks @tunisiano187 for taking this package over.
