### ISSUE TITLE
RFM - xolidosigndesktop

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-package-requests#864]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/xolidosigndesktop
Package source URL: https://gitlab.com/chocolatey-packages/automatic-updating/-/tree/master/automatic/xolidosigndesktop

**Comment by chtof** [comment]
@tunisiano187 
https://github.com/chocolatey-community/chocolatey-test-environment

It should be nice if you can have a Chocolatey Test environment. It allows to test a package in the same conditions than the package verifier. For example, this Chocolatey package currently fails due to a missing dependency on .NET framework.

When you will submit the corrected package, this test will also fails from the package verifier as dotnetfx package requires a reboot. You will have to ask to exempt this package from verifier tests.

**Comment by tunisiano187** [comment]
I've added this to my package, i'll send it as soon as i can upload it (currently refused, i don't really know why)
Thank you for the solution.
