### ISSUE TITLE
RFP - obsidian

### ISSUE THREAD

**Issue by brunelli** [chocolatey-community/chocolatey-package-requests#896]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://obsidian.md/
Direct download URL for the software / installer : https://github.com/obsidianmd/obsidian-releases/releases/download/v0.9.2/Obsidian.0.9.2.exe
Software summary / short description: Obsidian is a powerful knowledge base that works on top of a local folder of plain text Markdown files.

**Comment by AdmiringWorm** [comment]
Their EULA specifically denies any redistribution (https://obsidian.md/eula).
This do not mean that a package can not be created, but anyone wishing to pick up this request need to get explicit permission from the authors of the software first.

**Comment by teknowledgist** [comment]
This wouldn't require explicit permission if it's not an embedded package, would it?  A "normal" Chocolatey package that downloads the installer from the official distribution URL doesn't qualify as redistribution.

That said, while I'm not sure it deserves the "Blocked Upstream" label, the installer is strictly per-user (probably because of the limited, free license types).  It does **not** appear to be possible to make this a machine-install package which makes it a nope for me.

**Comment by dgalbraith** [comment]
@Jonasw234 has built a non-embedded package for [Obsidian](https://community.chocolatey.org/packages/obsidian) which is now available in the community repository.

I believe that the author is ok with a Chocolatey package / binaries being redistributed although I am not sure if the following would be acceptable from a moderation perspective?

![image](https://user-images.githubusercontent.com/1270002/115166521-8f5caf80-a0ab-11eb-9e5a-faefd43473e7.png)
