### ISSUE TITLE
RFP - webex

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#928]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.webex.com/unified-homepage-081220201.html
Direct download URL for the software / installer : https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex.msi
Software summary / short description:

All New Webex

In-person or afar, Webex brings everyone together to do exceptional work.

**Comment by houstdav000** [comment]
Note: This basically is the replacement for both webex-teams and webex-meetings, and so should be its own install probably

**Comment by houstdav000** [comment]
Correction: The Webex Teams app has replaced Webex Meetings, and they renamed it "Webex", with a _slightly_ different download link. Whether this means we can just alias "webex" to "webex-teams" or not, I'm not sure though

**Comment by AdmiringWorm** [comment]
@chtof this may perhaps be something you would want to look at.

If I understand everything correctly, then the `webex-teams` (and possibly `webex-meetings`) should be deprecated and replaced with a `webex` package.

If that is so, the best action is for the existing maintainer to deprecate those packages and submit a new one under the id `webex` instead of adding a package with a new maintainer.

As of right now, I won't be opening this request up to new maintainers, at least not yet.

**Comment by chtof** [comment]
@AdmiringWorm It seems it's not clear for everybody.
See also Disqus messages on https://chocolatey.org/packages/webex-meetings
We don't know exactly if it replaces Webex-Meetings or Webex-Teams, if it's a kind of merge of both or an additional software, some keypoints:
- According https://www.g2.com/compare/cisco-webex-meetings-vs-webex-formerly-webex-teams, webex would replace webex-teams (but I didn't understand why on the bottom of https://www.webex.com/downloads.html/ , the previous app is webex-meetings).
- According https://info.rpi.edu/multimedia-services/webex-meetings-webex-teams, Webex-Meetings and Webex-Teams are 2 different applications.

My opinion would be:
- To keep webex-meeting and webex-teams package while these applications are operational on the Webex network (if some users prefer to continue to use them as for example the "previous app" Webex-Meetings can be still downloaded, see at bottom of https://www.webex.com/downloads.html/ ).
- And to create a new package for "webex" as it's a new software name.

Other actions can be done later if needed when it will be clearer for all of us.

**Comment by AdmiringWorm** [comment]
@chtof looking at the links you provided, to me the appropriate choice is to deprecate only the `webex-teams` package in favour of a new `webex` package (due to the mention on their site that webex replaces webex-teams).
But to keep webex-meetings as it currently is, at least until there is an explicit mention on the website that webex replaces meetings.

Why webex-meetings is mentioned as a previous app could just be that the owners just tries to discourage the usage and instead use the `webex` app instead since it potentially makes them money (this is just my guess though).

**Comment by pauby** [comment]
Do we have an agreement on a way forward with this?

**Comment by houstdav000** [comment]
I think I'd be in agreement with @AdmiringWorm to deprecate `webex-teams` in favor of `webex` and keep `webex-meetings`

**Comment by AdmiringWorm** [comment]
@chtof are you in any position to push a `webex` package and deprecate the `webex-teams` package?

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/webex

**Comment by chtof** [comment]
@AdmiringWorm I wil deprecate webex-teams when webex will be approved. But if you agree, I will not add a dependency on webex-teams for webex as I am not sure the dependency will work correctly.

**Comment by AdmiringWorm** [comment]
@chtof since the `webex-teams` will be deprecated in favor of `webex`, it should have it as a dependency.
What I typically do if I believe there may be some issues, is to have a empty script in the deprecated package that writes out a warning it is deprecated and should be uninstalled by the user:

https://github.com/AdmiringWorm/chocolatey-packages/blob/master/deprecated/uplay/tools/chocolateyInstall.ps1#L3-L4

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/webex
