### ISSUE TITLE
RFP - frame.io-transfer

### ISSUE THREAD

**Issue by jhg21** [chocolatey-community/chocolatey-package-requests#942]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.frame.io/transfer/
Direct download URL for the software / installer : https://transferapp.frame.io/Frame.io-Transfer/6ab0c27d61d7cf8793b0357e6533ed81/latest/win32/x64/Frame.io+Transfer.exe
Software summary / short description: Frame.io Transfer is a collaboration platform that makes it easier to upload and download sophisticated folder structures and large files hosted on Frame.io.

**Comment by AdmiringWorm** [comment]
I am not so sure if `frame.io-transfer` would be the correct identifier for any package created for this request (the title of the issue should use the expected identifier of the package).

Need a second opinion on the id before opening this issue to maintainers.

/cc @pauby @gep13 @ferventcoder

**Comment by pauby** [comment]
@AdmiringWorm The `.io-transfer` is an invalid package name _unless_ the software is called that.

**Comment by AdmiringWorm** [comment]
@pauby I am well aware, how in this case I am uncertain if `frame.io` would be considered part of the software name, or if the software is just called `transfer`.

**Comment by pauby** [comment]
@AdmiringWorm That wasn't clear from your questions.

The software appears to be called Transfer and the company Frame.io (downloaded the software and inspected the MSI properties).

**Comment by jhg21** [comment]
@pauby Installing the program it is called `Frame.io Transfer` on Windows.
https://i.imgur.com/ggOC6Ho.png

But yes, the company is called Frame.io, but they themselves refer to the software as "Frame.io Transfer".

**Comment by AdmiringWorm** [comment]
> @pauby Installing the program it is called `Frame.io Transfer` on Windows.
> [i.imgur.com/ggOC6Ho.png](https://i.imgur.com/ggOC6Ho.png)
> 
> But yes, the company is called Frame.io, but they themselves refer to the software as "Frame.io Transfer".

This is the reason that makes me unsure, while personally I would probably have called the package `transfer` (if available) and left the `title` of the package as `Frame.io Transfer`, I would possibly think it can also be valid to name it as `frame.io-transfer` due to how it is referenced on the download page.

> Going further I would suggest that the title of the request is only an indication of what the package should be called. That should be down to the maintainer.

The title isn't meant as a hard requirement to an upcoming maintainer, but rather what the person opening the issue would expect (or want) to use when calling `choco install` (this is what I meant by `expected identifier of the package`).
The maintainer could decide to ignore that or follow it.
The title is also used by the validator in the repo to check for existing packages.

**Comment by AdmiringWorm** [comment]
In the interest of time, I have opened this request to maintainers without any modifications.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/transfer

**Comment by AdmiringWorm** [comment]
The package looks to have been approved.
