### ISSUE TITLE
RPM: Videostream package seem not maintained anymore.

### ISSUE THREAD

**Issue by boubou** [chocolatey-community/chocolatey-package-requests#943]
https://chocolatey.org/packages/videostream is bad checksums since many weeks/months.
I wrote to the maintainer privately, on his disqus wall and I opened an pull rtequest of his github.
[
![Untitled](https://user-images.githubusercontent.com/10491809/108728575-ba85b100-74f7-11eb-9026-62e366526053.png)
](url)
Can I be added as a maintainer on the package now ?
Thanks in advance.

**Comment by boubou** [comment]
What is missing ?

**Comment by AdmiringWorm** [comment]
Closing issue due to not following the template.
Please read the repository [`Readme.md`](https://cdn.getvideostream.com/videostream-native-updates/windows/x64/Setup.exe) file before opening any further issues.

Btw, the *PROOF* you show is a pull request to an unrelated repository, and not to the repository the maintainer of the package uses.

You also do not open an issue here to get added as a maintainer, it is an alternative when you do **NOT** want to be the maintainer.

**Comment by boubou** [comment]
Hi Kim,
Then can you point me in the right direction please ?

**Comment by AdmiringWorm** [comment]
In which regard?
Opening an RFM request for this repository?
Or opening a pull request to the correct repository?

I assume the latter.
The pull request needs to go into `https://github.com/CruzMarcio/au-packages`, which is linked to on the package details page. Instead, you opened a PR to `https://github.com/majkinetor/au-packages-template` probably due to how the repository is set up. The repository you should have made the PR to is a fork of the latter repository, and as such, when you open the pull request, you need to select the correct repository, instead of relying on the defaults.

Even if it were the correct repository, no maintainer would have accepted it due to the number of commits in the pull request (probably due to opening on the wrong repository).

If you meant regarding opening an RFM request, then please read through the [`Readme.md`](https://cdn.getvideostream.com/videostream-native-updates/windows/x64/Setup.exe) and fill out the template when you create an issue based on [`Maintainer Request template`](https://github.com/chocolatey-community/chocolatey-package-requests/issues/new?assignees=&labels=&template=mMaintainerRequest.md) (*remember to also read the comments in that template*).
