### ISSUE TITLE
RFM - nvidia-broadcast

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#966]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/nvidia-broadcast
Package source URL: https://github.com/madmoh/chocolatey-packages/tree/master/nvidia-broadcast

Date the maintainer was contacted (in YYYY-MM-DD): 2021-04-07
How the maintainer was contacted: Contact maintainer form. The maintainer responded and they are not interested in continuing to maintain the package.

**Comment by spitfire** [comment]
Any news on this?

**Comment by pauby** [comment]
@spitfire Just to be clear on the purpose of this repository.

This issue is highlighting that there is no active maintainer for the `nvidia-broadcast` and we have opened this to be available for other maintainers to pick up. Maintainers are volunteers who will pick this up if it interest them or they have time to maintain it. At the moment nobody has picked this up.

If this package interests you, my suggestion would be to take over maintenance and update it yourself. There is plenty of [documentation](https://docs.chocolatey.org) to help out.

**Comment by mikeee** [comment]
I'll have a look at picking up this package, will send the maintainer an email and I'll be back in 7 days.

**Comment by mikeee** [comment]
Package submitted, awaiting review. This package will require an exemption.

**Comment by mikeee** [comment]
Complete - package functional: https://community.chocolatey.org/packages/nvidia-broadcast#versionhistory

**Comment by TheCakeIsNaOH** [comment]
Thanks for taking the package over @mikeee
