### ISSUE TITLE
RFM - new-version-of-imageglass

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#971]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/imageglass
Package source URL: https://github.com/d2phap/ImageGlass/releases/tag/8.0.12.8

Date the maintainer was contacted (in YYYY-MM-DD):
How the maintainer was contacted:

Current software URL: https://imageglass.org/release/imageglass-8-1-4-18-home-31 or https://github.com/d2phap/ImageGlass/releases/tag/8.1.4.18

**Comment by AdmiringWorm** [comment]
Since there was no mention of how and when the maintainer was contacted, and the message from our bot was unanswered and due to the age of this issue, I will be closing this issue.

Please follow the package triage documentation for any further actions: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process
